apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ include "resource.default.name"  . }}-exceptions
  namespace: {{ include "resource.default.namespace"  . }}
spec:
  exceptions:
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root 
    - autogen-run-as-non-root
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  - policyName: disallow-capabilities-strict
    ruleNames:
    - adding-capabilities-strict
    - autogen-adding-capabilities-strict
    - require-drop-all
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - ReplicaSet
        - Pod
        namespaces:
        - {{ include "resource.default.namespace"  . }}
        names:
        - {{ include "resource.default.name"  . }}*